### ISSUE TITLE
Fix accelerometer return data

### ISSUE THREAD

**Issue by vitorleal** [telefonicadigital/kit-iot-wearable-node#1]
Accelerometer return data need to have the specific axis information. Ex:

#AC -10#30#14
#ACX -10
#ACY 30
#ACZ 14

**Comment by MatNeves** [comment]
Vitor,

O retorno do accelerometer, sem parametros, é um json inválido. É preciso adicionar aspas duplas para cada eixo.

Agora: { x: -3, y: -5, z: 10 }
Correto: { "x": -3, "y": -5, "z": 10 }

fonte: http://www.json.org/json-pt.html
